version: '3.9'

services:
  # nginx
  nginx:
    image: nginx:1.19-alpine
    container_name: nginx_server_sanctum
    ports:
      - ８０:80
    environment:
      TZ: Asia/Tokyo
    volumes:
      - ./api:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api

  # API
  api: &api
    container_name: api_sanctum
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    volumes:
      - ./api:/var/www/html
    environment:
      TZ: Asia/Tokyo
    expose:
      - 9000
    tty: true
    depends_on:
      - database

  # database
  database:
    container_name: database_sanctum
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_db
      TZ: Asia/Tokyo
    volumes:
      - docker-db-mysql:/var/lib/mysql
      - ./docker/db/sql:/docker-entrypoint-initdb.d

  # 開発用DBエディタ
  phpmyadmin:
    container_name: phpmyadmin_sanctum
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_HOSTS=database
      - PMA_USER=root
      - PMA_PASSWORD=root

  # 開発メールテスト用
  mail:
    image: mailhog/mailhog
    container_name: mail_dgm
    ports:
      - 8025:8025

volumes:
  docker-db-mysql: